### ISSUE TITLE
Update pod in specs repo

### ISSUE THREAD

**Issue by vincentjames501** [iosphere/ISHPermissionKit#26]
Awesome library. Makes dealing with permissions much easier! Right now #22 is biting us, could you please update this pod to a new version so I don't have to manually target this repo in my Podfile? Cheers!

**Comment by felixLam** [comment]
We have updated the pod specs to 0.8.0. Please try http://cocoapods.org/pods/ISHPermissionKit

**Comment by felixLam** [comment]
Thanks for the compliments.
