### ISSUE TITLE
requesting permissions outside of the RequestViewController

### ISSUE THREAD

**Issue by VonD** [iosphere/ISHPermissionKit#36]
Hello,

Many thanks for this great lib!

I'm having trouble using the `ISHPermissionRequest ` to request some permissions outside of the `ISHPermissionsViewController `.

#### Location

The iOS alert does show up, but disappears before the user has had a chance to choose. Here's my code :

```objective-c
ISHPermissionRequest *requestManager = [ISHPermissionRequest requestForCategory:ISHPermissionCategoryLocationWhenInUse];
    [requestManager requestUserPermissionWithCompletionBlock:^(ISHPermissionRequest *request, ISHPermissionState state, NSError *error){
      if (error || state != 200) {
        NSLog(@"Permission denied");
      } else {
        NSLog(@"Permission granted")
      }
    }];
```

#### Remote notifications

The iOS alert show up and stays till the user chooses, but the completion block is not called unless I call the method a second time. Here's my code : 

```objective-c
ISHPermissionRequest *requestManager = [ISHPermissionRequest requestForCategory:ISHPermissionCategoryNotificationRemote];
    [requestManager requestUserPermissionWithCompletionBlock:^(ISHPermissionRequest *request, ISHPermissionState state, NSError *error){
      if (error || state != 200) {
        NSLog(@"Permission denied");
      } else {
        NSLog(@"Permission granted")
      }
    }];
```

Is there anything i am doing wrong or not getting ?

Many thanks for your help

**Comment by felixLam** [comment]
Hi VonD,

the code above might not be complete, but do you maintain a strong reference to the `ISHPermissionRequest` after the initialization. E.g. if you initiate the request in a view controller try holding it in a `strong` property until the request completes.

Did this help? If not can you provide some more context as to how you use the requests.

Is there a particular reason why you do not use the `ISHPermissionsViewController`?

Kind regards,

Felix

**Comment by felixLam** [comment]
Given that I did not hear back, I am going to close this issue. Feel free to re-open it later with more information on your implementation.
