### ISSUE TITLE
Facebook permission denied on second attempt if no account data on first attempt

### ISSUE THREAD

**Issue by danhalliday** [iosphere/ISHPermissionKit#52]
Thanks for all hard work on this library.

I'm trying the Facebook permission. If the permission is requested and the user has not filled in their account in Settings, the request failed with `Denied`, as expected.

I then direct the user to their Facebook account settings. If they add their account in Settings and return to my app, further requests for the Facebook permissions fail with `Denied`.

Is this a bug or some known behaviour?

**Update**:
I should add, when viewing the Facebook screen in Settings, my app is not listed under `allow these apps to use your account`, so it seems after ISHPermissionKit's first failed request, it never again tries to request access from the system (caching the original result as a denial, rather than just a lack of account?)

**Comment by felixLam** [comment]
Hi @danhalliday,

thank you for the elaborate Bug Report. We do indeed cache the initial response:
https://github.com/iosphere/ISHPermissionKit/blob/master/ISHPermissionKit/Requests/ISHPermissionRequestAccount.m#L84

We currently do not check the error. Let me investigate if it contains an error if the user has no account or if we can determine ahead of time if the user has one.

Brb

**Comment by danhalliday** [comment]
I can confirm the error due to no Facebook account details present is: `Error Domain=com.apple.accounts Code=6 "(null)"`. As far as I can see no `userInfo` is provided.

**Comment by felixLam** [comment]
Yup. Just got that too. 6 is equal to `ACErrorAccountNotFound`

**Comment by felixLam** [comment]
There currently is no way to bubble this error up. We could "for now" post a notification.

**Comment by felixLam** [comment]
We could then leave the state in `ISHPermissionStateAskAgain`. This would however present the alert again unless you provide a button that calls `changePermissionStateToDontAskFromSender:`.

**Comment by danhalliday** [comment]
Yes. I guess that has the problem that the user wouldn't know there was a problem. Perhaps `ISHPermissionStateUnsupported` is a better fit, but I see from the comment its usage is more specific to hardware support rather than the software configuration.

**Comment by felixLam** [comment]
I thought about that too, but then you would never ask a user again. And we can't be notified of him/her adding a facebook to reset that state (other than asking the system for permission again).

**Comment by felixLam** [comment]
We will need to bubble the error up and avoid setting the state to anything but unknown. It would then be the responsibility of the implementing app to avoid calling for facebook (or other erroring) permissions again and again.

**Comment by danhalliday** [comment]
Well as my use case is just using the API (not the view controllers), I already get the error propagated in the `requestUserPermissionWithCompletionBlock` callback, so I can set my own UI to direct the user to fill in their account.

I guess the real problem is not being 'allowed' to try again with the next request. Perhaps another approach would be to allow a request without using the cache? (I could well be misunderstanding the logic a bit here).

**Comment by felixLam** [comment]
The basic problem with this particular permission is that apple does not provide a way to check if the permission has been granted without asking for it. This is why we rely on the cache here. If have created a PR that fixes the caching issue and provides an error callback for users who use the view controllers too. Can you check if that works for you?

**Comment by danhalliday** [comment]
Sure I'll take a look at that tonight. Many thanks for the quick response and for the project — Apple's APIs here are really tricky to deal with!

**Comment by felixLam** [comment]
This should be fixed with #53. I will prepare a new release 1.2.0. Feel free to reopen this issue if this does not fix the issue for you.

**Comment by felixLam** [comment]
Thanks again for bringing this to our attention and providing such a detailed bug report. 👍 @danhalliday

**Comment by danhalliday** [comment]
I have had chance to test this properly now, and can confirm it solves my use case. Many thanks!
