### ISSUE TITLE
Styling?

### ISSUE THREAD

**Issue by rlaferla** [iosphere/ISHPermissionKit#82]
Is there an alternate styling for ISHPermissionKit?  I need something a bit more plain (or even sophisticated) than the thick blue bordered action sheet.

**Comment by felixLam** [comment]
Hi @rlaferla That is the whole idea of ISHPermissionKit. You can customise the look by instantiating a custom ´ISHPermissionRequestViewController´Subclass in the dataSource. The super class provides convenient IBActions.
