### ISSUE TITLE
Permission Categories Not Resolving

### ISSUE THREAD

**Issue by emaddoma** [iosphere/ISHPermissionKit#87]
My Swift 3.0 project isn't resolving any of the permission categories.  ISHPermissionKit installed as a Dynamically-Linked Framework.

<img width="1158" alt="screen shot 2016-10-26 at 4 37 47 pm" src="https://cloud.githubusercontent.com/assets/12914515/19749030/914d2434-9b9a-11e6-9d36-aaf3275f29ee.png">

Any suggestions?

**Comment by shagedorn** [comment]
We had to rethink the framework's build process in order to comply with iTunes Connect changes. Have you read the new README? Which integration (CocoaPods? Carthage? Manuallly?) are you using?

**Comment by shagedorn** [comment]
We had to change the framework's build process to comply with changes in iTunes Connect. Did you study the revised README file already? If you continue to have issues, please let us know which integration method (CocoaPods, Carthage, manually) you are using.

**Comment by emaddoma** [comment]
I had originally set it up manually.  It was only the categories that would not resolve.  I changed to using CocoaPods and it worked fine.

**Comment by shagedorn** [comment]
I would assume you forgot to use the configuration file in your app. While the framework builds fine as long as you place the config file in the right directory, your app also needs to know about the build configuration, else autocompletion won't see all symbols.

**Comment by emaddoma** [comment]
I did the configuration file and fairly certain I put it in the correct location.  Would the build fail without having one placed properly?

**Comment by shagedorn** [comment]
The build wouldn't fail, but the framework wouldn't include any useful code either. Apart from putting the file in the right location, did you also set the configuration file for your app's project, as depictured here?

![config](https://github.com/iosphere/ISHPermissionKit/raw/master/assets/config_file.png)

We also provide a sample app that includes all necessary steps:

https://github.com/iosphere/ISHPermissionKitSampleApp

**Comment by emaddoma** [comment]
That's what I missed.  Thanks for your time.
