### ISSUE TITLE
Push notification arriving, but not waking device?

### ISSUE THREAD

**Issue by emaddoma** [iosphere/ISHPermissionKit#89]
If I send my app a push, it's always received.  Alerts appear outside the app.  Alerts appear on the lock screen. However, if the device is locked and the screen is off, the push to my app doesn't wake the device and play sound like my other apps do.  Am I missing something?

**Comment by h3smith** [comment]
This is a bug within iOS. lock screen pushes can be very delayed.

**Comment by emaddoma** [comment]
Ah, good to know!
