### ISSUE TITLE
When are you planning to release new version of ISHPermissionKit?

### ISSUE THREAD

**Issue by VladKorzun** [iosphere/ISHPermissionKit#93]
When are you planning to release new version of ISHPermissionKit? I think this fix https://github.com/iosphere/ISHPermissionKit/commit/e7edcea14d65230c4e2a65e2a42f72ef94b6d9b7 should go to production ASAP 

Thanks!

**Comment by natanrolnik** [comment]
I'm facing the same problem. I would suggest using submodules, or pointing CocoaPods to use the commit in master...

**Comment by natanrolnik** [comment]
In case anyone needs it:

`pod 'ISHPermissionKit', :git => 'https://github.com/iosphere/ISHPermissionKit.git', :commit => '3685ef190e8d246668df1e90bf914b2b4ad16124'`
